// Structured resume content for the downloadable PDF, in both languages.
// Authored to mirror the site (lib/data.ts / lib/projects.ts) plus the extra
// detail from the full CVs. Re-run scripts/generate-resume.mjs after editing.

export const contact = {
  name: "Luis Felipe Volpato Alves",
  email: "mail.for.luis.alves@gmail.com",
  phone: "(415) 272-9149",
  linkedin: "linkedin.com/in/luisfvalves",
  github: "github.com/finxster",
  site: "https://finx.dev",
};

export const content = {
  en: {
    role: "Staff Software Engineer · Technical Lead · AI Engineering",
    location: "SF Bay Area, USA",
    labels: {
      summary: "Summary",
      skills: "Technical Skills",
      experience: "Professional Experience",
      ventures: "Entrepreneurial Experience",
      education: "Education",
      languages: "Languages",
      certifications: "Certifications",
      client: "Client",
      tech: "Tech",
      present: "Present",
    },
    summary:
      "Staff Software Engineer with 21+ years of experience designing, building, and operating software across enterprise and startup environments. Specialized in backend systems, distributed architectures, enterprise integrations, and AI-enabled engineering practices. Over the last decade, I have led technical initiatives spanning microservices, data platforms, supply chain systems, financial applications, and developer productivity programs for Fortune 500 organizations. I regularly operate across architecture, implementation, mentoring, and cross-functional collaboration. Alongside enterprise work, I have founded and co-founded multiple ventures, including X4Fare, PayAqui, fleeber (now amy.network), and AtipicALI. I enjoy turning ambiguity into shipped products and helping teams deliver sustainable, scalable solutions.",
    skills: [
      { group: "Backend", items: "Java (8–21), Spring Boot, Spring WebFlux, Kafka, Hibernate, Python, REST APIs, JMS, SOAP" },
      { group: "Frontend & Mobile", items: "React, TypeScript, JavaScript, Flutter, Swift (iOS), Android" },
      { group: "Cloud & Data", items: "AWS (EC2, RDS, SQS, S3), Databricks, PostgreSQL, Oracle, SQL Server" },
      { group: "DevOps & Tooling", items: "GitHub Actions, Jenkins, Bamboo, Maven, Gradle, Git, Liquibase, CI/CD" },
      { group: "AI & Engineering Practices", items: "AI / LLMs, Agentic AI, Prompt Engineering, AI-Assisted Development, GitHub Copilot, Codex, TDD/BDD, Scrum, Kanban" },
    ],
    experience: [
      {
        company: "Avenue Code",
        title: "Staff Software Engineer · Tech Lead",
        place: "SF Bay Area, USA",
        period: "2022 – Present",
        bullets: [
          "Lead technical initiatives across supply chain, logistics, data engineering, and AI programs for Fortune 500 retail organizations.",
          "Built the proof of concept for a strategic internal rules platform, helping leadership evaluate the replacement of a commercial solution and establishing a foundation for future AI-driven capabilities.",
          "Coordinated the migration of approximately 20 microservices from Java 11 to Java 21, defining technical standards, rollout guidelines, and adoption practices across multiple teams.",
          "Designed and implemented an engineering operations dashboard providing visibility into service health, deployment readiness, and environment availability across the organization.",
          "Contributed to the company's AI engineering initiatives through development workflows, prompting strategies, implementation standards, and engineering enablement practices.",
          "Developed data processing, simulation, and forecasting solutions using Python and Databricks for retail planning and supply-chain optimization.",
        ],
        tech: "Java, Spring Boot, Spring WebFlux, Python, Databricks, AWS, Kafka, Drools, SQL Server, Oracle, Jenkins, AI-assisted development",
      },
      {
        company: "X4Fare",
        title: "Founding Engineer",
        place: "São Paulo, Brazil — Remote",
        period: "2020 – 2021",
        bullets: [
          "Joined as one of the first engineers and helped build a transit fintech startup from concept to production.",
          "Delivered backend services, web applications, and mobile solutions supporting digital wallet and transaction processing products.",
          "Learned Flutter and became a key contributor to the mobile platform, accelerating delivery during the company's early growth stage.",
          "Participated in hiring, onboarding, mentoring, and technical decision-making as the engineering team expanded.",
          "Acted as a cross-functional technical reference across backend, mobile, operations, and product discussions.",
        ],
        tech: "Java, Spring Boot, Flutter, React, AWS, JHipster, Liquibase, GitHub Actions",
      },
      {
        company: "Avenue Code",
        title: "Senior Software Engineer · Tech Lead",
        place: "São Paulo, Brazil → USA",
        period: "2015 – 2020",
        bullets: [
          "SquareTrade: one of the first three engineers to start the account in Brazil — the work grew the team to 30+ people. Worked on Merchant Integrations (Apache Camel, Apache Zookeeper); acted as Tech Lead, Scrum Master, and 'Buddy' (managerial mentoring role).",
          "Merchant e-Solutions: traveled to Redwood City, CA to help the company achieve AMEX certification, working on-site.",
          "Williams Sonoma: built microservices on top of a Sterling application layer; helped the team build dashboards in pure JS/HTML plus Bash scripts.",
          "GAP · PIM / Data Governance: led and mentored the team on unit and integration tests for Kafka, replacing the product catalog (Pacman) with Stibo and publishing standardized data into a Kafka cluster; also served as Management Mentor.",
        ],
        tech: "Java, Spring Boot, Kafka, JMS, SOAP, Apache Camel, EJB, JUnit, Mockito, Gradle, Swagger, Bash, Jenkins, Oracle, SQL Server, PostgreSQL",
      },
      {
        company: "MAPS Soluções e Serviços",
        title: "Senior Software Engineer · Tech Lead",
        place: "São Paulo, Brazil",
        period: "2005 – 2015",
        bullets: [
          "Designed and implemented a tax calculation engine for investment fund liability management, a core business component that remains in production today.",
          "Led development of financial and regulatory solutions supporting banking and investment-fund operations.",
          "Worked directly with clients and business stakeholders to translate complex regulatory requirements into software solutions.",
          "Served in technical leadership roles across multiple projects, including engineering leadership, mentoring, backlog prioritization, delivery coordination, and architecture discussions.",
          "Mentored approximately twenty engineers throughout multiple projects and teams over a ten-year period.",
        ],
        tech: "Java, Spring, Hibernate, Oracle, PostgreSQL, AWS, Wicket, Maven, Jenkins",
      },
      {
        company: "Faculdade Cásper Líbero",
        title: "IT Intern",
        place: "São Paulo, Brazil",
        period: "2002 – 2005",
        bullets: [
          "Maintained the university's computer labs, supported students with technical issues, and automated administrative routines.",
        ],
        tech: "Bash Scripting, JavaScript",
      },
    ],
    ventures: [
      {
        name: "AtipicALI",
        title: "Co-founder",
        period: "2025 – Present",
        desc: "Building a platform focused on helping neurodivergent individuals discover and evaluate services, places, and resources. Responsible for product architecture and implementation across backend, web, administration, and AI-assisted development workflows. Designing and operating the platform using Java, Spring Boot, Vue, Cloudflare, PostgreSQL, and modern AI-assisted engineering practices.",
      },
      {
        name: "PayAqui",
        title: "Founding Engineer · Mobile",
        period: "2018 – 2019",
        desc: "Founding engineer of a side payments venture. Designed and built the native Android and iOS apps end to end — from architecture to shipping — while also owning requirements discovery and UX, and contributing to the Java backend.",
      },
      {
        name: "fleeber (now amy.network)",
        title: "Co-founder",
        period: "2013 – 2015",
        desc: "Co-founded a social network for musicians with three applications (public app, back-office, and Studios ERP). Responsible for all technical decisions and most of the development, using a BDD approach, an Apache Lucene search engine, and AWS infrastructure. Continues today as amy.network.",
      },
    ],
    education: [
      { degree: "Bachelor in Computer Science", school: "Pontifical Catholic University of São Paulo (PUC-SP)", period: "2002 – 2009" },
    ],
    languages: "Portuguese (native/bilingual) · English (full professional proficiency)",
    certifications: [
      "PSM — Professional Scrum Master, Scrum.org (2017)",
      "MCD — Integration & API Associate, MuleSoft (2018)",
      "KMP I — Kanban Management Professional, Kanban University (2015)",
      "Building High-Performing Teams, Stanford University (2020)",
      "An Introduction to Agile Project Management, Stanford University (2020)",
      "Swift & TDD/Unit tests, Managing projects with Scrum (Alura, 2015) · UX & Usability (Adaptworks, 2014)",
    ],
  },

  pt: {
    role: "Staff Software Engineer · Technical Lead · AI Engineering",
    location: "SF Bay Area, EUA",
    labels: {
      summary: "Resumo",
      skills: "Competências Técnicas",
      experience: "Experiência Profissional",
      ventures: "Experiência Empreendedora",
      education: "Formação",
      languages: "Idiomas",
      certifications: "Certificações",
      client: "Cliente",
      tech: "Tecnologias",
      present: "Atual",
    },
    summary:
      "Staff Software Engineer com mais de 21 anos de experiência projetando, construindo e operando software em ambientes corporativos e de startup. Especializado em sistemas backend, arquiteturas distribuídas, integrações corporativas e práticas de engenharia habilitadas por IA. Na última década, liderei iniciativas técnicas envolvendo microsserviços, plataformas de dados, sistemas de supply chain, aplicações financeiras e programas de produtividade de engenharia para organizações Fortune 500. Atuo regularmente em arquitetura, implementação, mentoria e colaboração multidisciplinar. Em paralelo ao trabalho corporativo, fundei e cofundei diversos empreendimentos, incluindo X4Fare, PayAqui, fleeber (hoje amy.network) e AtipicALI. Gosto de transformar ambiguidade em produtos entregues e de ajudar times a entregar soluções sustentáveis e escaláveis.",
    skills: [
      { group: "Backend", items: "Java (8–21), Spring Boot, Spring WebFlux, Kafka, Hibernate, Python, REST APIs, JMS, SOAP" },
      { group: "Frontend & Mobile", items: "React, TypeScript, JavaScript, Flutter, Swift (iOS), Android" },
      { group: "Cloud & Dados", items: "AWS (EC2, RDS, SQS, S3), Databricks, PostgreSQL, Oracle, SQL Server" },
      { group: "DevOps & Ferramentas", items: "GitHub Actions, Jenkins, Bamboo, Maven, Gradle, Git, Liquibase, CI/CD" },
      { group: "IA & Práticas de Engenharia", items: "IA / LLMs, IA Agentic, Prompt Engineering, Desenvolvimento Assistido por IA, GitHub Copilot, Codex, TDD/BDD, Scrum, Kanban" },
    ],
    experience: [
      {
        company: "Avenue Code",
        title: "Staff Software Engineer · Tech Lead",
        place: "SF Bay Area, EUA",
        period: "2022 – Atual",
        bullets: [
          "Lidero iniciativas técnicas em supply chain, logística, engenharia de dados e programas de IA para organizações de varejo Fortune 500.",
          "Construí a prova de conceito de uma plataforma de regras interna estratégica, ajudando a liderança a avaliar a substituição de uma solução comercial e estabelecendo a base para futuras capacidades orientadas a IA.",
          "Coordenei a migração de aproximadamente 20 microsserviços de Java 11 para Java 21, definindo padrões técnicos, diretrizes de rollout e práticas de adoção em múltiplos times.",
          "Projetei e implementei um dashboard de operações de engenharia com visibilidade sobre saúde dos serviços, prontidão de deploy e disponibilidade de ambientes em toda a organização.",
          "Contribuí para as iniciativas de engenharia de IA da empresa por meio de workflows de desenvolvimento, estratégias de prompting, padrões de implementação e práticas de capacitação de engenharia.",
          "Desenvolvi soluções de processamento, simulação e forecasting de dados usando Python e Databricks para planejamento de varejo e otimização de supply chain.",
        ],
        tech: "Java, Spring Boot, Spring WebFlux, Python, Databricks, AWS, Kafka, Drools, SQL Server, Oracle, Jenkins, desenvolvimento assistido por IA",
      },
      {
        company: "X4Fare",
        title: "Engenheiro Fundador",
        place: "São Paulo, Brasil — Remoto",
        period: "2020 – 2021",
        bullets: [
          "Entrei como um dos primeiros engenheiros e ajudei a construir uma startup de fintech de mobilidade do conceito à produção.",
          "Entreguei serviços de backend, aplicações web e soluções mobile dando suporte a produtos de carteira digital e processamento de transações.",
          "Aprendi Flutter e me tornei um contribuidor-chave da plataforma mobile, acelerando a entrega durante o estágio inicial de crescimento da empresa.",
          "Participei de contratação, onboarding, mentoria e decisões técnicas conforme o time de engenharia crescia.",
          "Atuei como referência técnica multidisciplinar em discussões de backend, mobile, operações e produto.",
        ],
        tech: "Java, Spring Boot, Flutter, React, AWS, JHipster, Liquibase, GitHub Actions",
      },
      {
        company: "Avenue Code",
        title: "Engenheiro de Software Sênior · Tech Lead",
        place: "São Paulo, Brasil → EUA",
        period: "2015 – 2020",
        bullets: [
          "SquareTrade: um dos três primeiros engenheiros a iniciar a conta no Brasil — o trabalho fez o time crescer para mais de 30 pessoas. Atuei em Merchant Integrations (Apache Camel, Apache Zookeeper) como Tech Lead, Scrum Master e 'Buddy' (papel gerencial de mentoria).",
          "Merchant e-Solutions: viajei para Redwood City, CA para ajudar a empresa a obter a certificação AMEX, trabalhando on-site.",
          "Williams Sonoma: construí microsserviços sobre uma camada de aplicação Sterling; ajudei o time a montar dashboards em JS/HTML puro e scripts em Bash.",
          "GAP · PIM / Data Governance: liderei e mentorei o time em testes unitários e de integração para Kafka, substituindo o catálogo de produtos (Pacman) pelo Stibo e publicando dados padronizados em um cluster Kafka; também atuei como Management Mentor.",
        ],
        tech: "Java, Spring Boot, Kafka, JMS, SOAP, Apache Camel, EJB, JUnit, Mockito, Gradle, Swagger, Bash, Jenkins, Oracle, SQL Server, PostgreSQL",
      },
      {
        company: "MAPS Soluções e Serviços",
        title: "Engenheiro de Software Sênior · Tech Lead",
        place: "São Paulo, Brasil",
        period: "2005 – 2015",
        bullets: [
          "Projetei e implementei um motor de cálculo de impostos para controle de passivo de fundos de investimento, um componente central de negócio que segue em produção até hoje.",
          "Liderei o desenvolvimento de soluções financeiras e regulatórias para operações bancárias e de fundos de investimento.",
          "Trabalhei diretamente com clientes e stakeholders de negócio para traduzir requisitos regulatórios complexos em soluções de software.",
          "Atuei em papéis de liderança técnica em múltiplos projetos, incluindo liderança de engenharia, mentoria, priorização de backlog, coordenação de entregas e discussões de arquitetura.",
          "Mentorei aproximadamente vinte engenheiros ao longo de múltiplos projetos e times durante um período de dez anos.",
        ],
        tech: "Java, Spring, Hibernate, Oracle, PostgreSQL, AWS, Wicket, Maven, Jenkins",
      },
      {
        company: "Faculdade Cásper Líbero",
        title: "Estagiário de TI",
        place: "São Paulo, Brasil",
        period: "2002 – 2005",
        bullets: [
          "Mantinha os laboratórios de informática da faculdade, dava suporte técnico aos alunos e automatizava rotinas administrativas.",
        ],
        tech: "Bash Scripting, JavaScript",
      },
    ],
    ventures: [
      {
        name: "AtipicALI",
        title: "Cofundador",
        period: "2025 – Atual",
        desc: "Construindo uma plataforma focada em ajudar pessoas neurodivergentes a descobrir e avaliar serviços, lugares e recursos. Responsável pela arquitetura e implementação do produto em backend, web, administração e workflows de desenvolvimento assistido por IA. Projeto e opero a plataforma com Java, Spring Boot, Vue, Cloudflare, PostgreSQL e práticas modernas de engenharia assistida por IA.",
      },
      {
        name: "PayAqui",
        title: "Engenheiro Fundador · Mobile",
        period: "2018 – 2019",
        desc: "Engenheiro fundador de uma fintech de pagamentos tocada em paralelo. Projetei e construí os apps nativos Android e iOS de ponta a ponta — da arquitetura à publicação — participando também da descoberta de requisitos e UX, além de contribuir com o backend em Java.",
      },
      {
        name: "fleeber (hoje amy.network)",
        title: "Cofundador",
        period: "2013 – 2015",
        desc: "Cofundei uma rede social para músicos com três aplicações (app público, back-office e o ERP Studios). Responsável por todas as decisões técnicas e a maior parte do desenvolvimento, com abordagem BDD, motor de busca em Apache Lucene e infraestrutura na AWS. Continua hoje como amy.network.",
      },
    ],
    education: [
      { degree: "Bacharelado em Ciência da Computação", school: "Pontifícia Universidade Católica de São Paulo (PUC-SP)", period: "2002 – 2009" },
    ],
    languages: "Português (nativo/bilíngue) · Inglês (proficiência profissional plena)",
    certifications: [
      "PSM — Professional Scrum Master, Scrum.org (2017)",
      "MCD — Integration & API Associate, MuleSoft (2018)",
      "KMP I — Kanban Management Professional, Kanban University (2015)",
      "Building High-Performing Teams, Stanford University (2020)",
      "An Introduction to Agile Project Management, Stanford University (2020)",
      "Swift & TDD/testes unitários, Gestão de projetos com Scrum (Alura, 2015) · UX & Usabilidade (Adaptworks, 2014)",
    ],
  },
};
