// Structured resume content for the downloadable PDF, in both languages.
// Authored to mirror the site (lib/data.ts / lib/projects.ts) plus the extra
// detail from the full CVs. Re-run scripts/generate-resume.mjs after editing.

export const contact = {
  name: "Luis Felipe Volpato Alves",
  email: "mail.for.luis.alves@gmail.com",
  phone: "(415) 272-9149",
  linkedin: "linkedin.com/in/luisfvalves",
  github: "github.com/finxster",
  site: "finx.dev",
};

export const content = {
  en: {
    role: "Staff Software Engineer · Tech Lead · Scrum Master",
    location: "SF Bay Area, USA",
    labels: {
      summary: "Summary",
      skills: "Technical Skills",
      experience: "Professional Experience",
      ventures: "Entrepreneurial Ventures",
      education: "Education",
      languages: "Languages",
      certifications: "Certifications",
      client: "Client",
      tech: "Tech",
      present: "Present",
    },
    summary:
      "Senior software engineer with 17+ years across the full software lifecycle — UX, analysis, design, development, testing, and deployment. Experienced on backend-only, backend + frontend, and backend + mobile projects, acting as Developer, Tech Lead, or Scrum Master / Agile facilitator depending on the team's needs. Strong entrepreneurial streak: founding engineer at X4Fare and PayAqui, co-founder of fleeber (now amy.network), and currently building AtipicALI. I lead by example, enjoy working with non-technical stakeholders, and turn ambiguity into shipped products.",
    skills: [
      { group: "Backend", items: "Java (8–21), Spring Boot, Spring WebFlux, Kafka, Hibernate, Drools, Python, REST, JMS, SOAP" },
      { group: "Frontend & Mobile", items: "React, TypeScript, JavaScript, Flutter, Swift (iOS), Android, JSF, Wicket" },
      { group: "Cloud & Data", items: "AWS (EC2, RDS, SQS, S3), Databricks, Oracle, SQL Server, PostgreSQL" },
      { group: "DevOps & Tooling", items: "CI/CD, GitHub Actions, Jenkins, Bamboo, Maven, Gradle, Git, Liquibase, JHipster" },
      { group: "AI & Practices", items: "AI / LLMs, Agentic AI, GitHub Copilot, Codex, TDD/BDD, JUnit, Mockito, Scrum, Kanban" },
    ],
    experience: [
      {
        company: "Avenue Code",
        title: "Staff Software Engineer · Tech Lead",
        place: "SF Bay Area, USA — Remote",
        period: "2022 – Present",
        bullets: [
          "Lead technical initiatives across supply chain, logistics, data engineering, and AI programs for Fortune 500 retail organizations.",
          "Built the proof of concept for a strategic internal rules platform, helping leadership validate the replacement of a commercial solution and establish the foundation for future AI initiatives.",
          "Coordinated the migration of approximately 20 microservices from Java 11 to Java 21, defining technical guidelines, documentation, and rollout practices.",
          "Designed and implemented an operational engineering dashboard adopted across multiple teams, providing visibility into service health, deployment status, and environment availability.",
          "Implemented automated Jira workflows for operational incident tracking and service monitoring.",
          "Contributed to AI-assisted engineering practices through development workflows, prompts, documentation, and implementation standards.",
          "Developed data processing and simulation solutions using Python and Databricks for retail planning and forecasting initiatives.",
        ],
        tech: "Java, Spring Boot, Spring WebFlux, Python, Databricks, AWS, Kafka, Drools, SQL Server, Oracle, Jenkins, AI-assisted development",
      },
      {
        company: "X4Fare",
        title: "Founding Engineer",
        place: "São Paulo, Brazil — Remote",
        period: "2020 – 2021",
        bullets: [
          "Helped build an early-stage transit fintech startup from concept to production deployments.",
          "Delivered backend, web, and mobile applications supporting digital wallet and transaction processing products.",
          "Learned Flutter and became a key contributor to the mobile platform to accelerate product delivery.",
          "Participated in hiring, interviewing, onboarding, and mentoring engineers as the team expanded.",
          "Created onboarding processes that enabled new developers to contribute production code within approximately two weeks.",
          "Acted as a technical reference across backend, mobile, and product discussions.",
          "Supported deployment and operation of customer-facing production systems.",
        ],
        tech: "Java, Spring Boot, Flutter, React, AWS, JHipster, Liquibase, GitHub Actions",
      },
      {
        company: "Avenue Code",
        title: "Senior Software Engineer · Tech Lead",
        place: "São Paulo, Brazil → USA",
        period: "2015 – 2020",
        bullets: [
          "SquareTrade: one of the first three engineers to start the account in Brazil — the work grew the team to 30+ people. Worked on Merchant Integrations (Apache Camel, Apache Zookeeper); acted as Tech Lead, Scrum Master, and 'Buddy' (managerial mentoring role).",
          "Merchant e-Solutions: traveled to Redwood City, CA to help the company achieve AMEX certification, working on-site.",
          "Williams Sonoma: built microservices on top of a Sterling application layer; helped the team build dashboards in pure JS/HTML plus Bash scripts.",
          "GAP · PIM / Data Governance: led and mentored the team on unit and integration tests for Kafka, replacing the product catalog (Pacman) with Stibo and publishing standardized data into a Kafka cluster; also served as Management Mentor.",
        ],
        tech: "Java, Spring Boot, Kafka, JMS, SOAP, Apache Camel, EJB, JUnit, Mockito, Gradle, Swagger, Bash, Jenkins, Oracle, SQL Server, PostgreSQL",
      },
      {
        company: "MAPS Soluções e Serviços",
        title: "Senior Software Engineer · Tech Lead",
        place: "São Paulo, Brazil",
        period: "2005 – 2015",
        bullets: [
          "Designed and implemented a tax calculation engine used for liability control of investment funds.",
          "Led development of regulatory and business-critical features for financial systems serving banking clients.",
          "Acted as technical lead, scrum master, product owner, and mentor depending on project needs.",
          "Gathered requirements directly from clients, prioritized backlogs, and translated business rules into software solutions.",
          "Mentored approximately twenty engineers throughout multiple projects and teams.",
          "Participated in architecture discussions, technical planning, and delivery coordination for financial platforms.",
        ],
        tech: "Java, Spring, Hibernate, Oracle, PostgreSQL, AWS, Wicket, Maven, Jenkins",
      },
      {
        company: "Faculdade Cásper Líbero",
        title: "IT Intern",
        place: "São Paulo, Brazil",
        period: "2002 – 2005",
        bullets: [
          "Maintained the university's computer labs, supported students with technical issues, and automated administrative routines.",
        ],
        tech: "Bash Scripting, JavaScript",
      },
    ],
    ventures: [
      {
        name: "AtipicALI",
        title: "Co-founder",
        period: "2025 – Present",
        desc: "An active parallel venture started in 2025 alongside full-time work, still running today.",
      },
      {
        name: "PayAqui",
        title: "Founding Engineer · Mobile",
        period: "2018 – 2019",
        desc: "Founding engineer of a side payments venture. Designed and built the native Android and iOS apps end to end — from architecture to shipping — while also owning requirements discovery and UX, and contributing to the Java backend.",
      },
      {
        name: "fleeber (now amy.network)",
        title: "Co-founder",
        period: "2013 – 2015",
        desc: "Co-founded a social network for musicians with three applications (public app, back-office, and Studios ERP). Responsible for all technical decisions and most of the development, using a BDD approach, an Apache Lucene search engine, and AWS infrastructure. Continues today as amy.network.",
      },
    ],
    education: [
      { degree: "Bachelor in Computer Science", school: "Pontifical Catholic University of São Paulo (PUC-SP)", period: "2002 – 2009" },
    ],
    languages: "Portuguese (native/bilingual) · English (full professional proficiency)",
    certifications: [
      "PSM — Professional Scrum Master, Scrum.org (2017)",
      "MCD — Integration & API Associate, MuleSoft (2018)",
      "KMP I — Kanban Management Professional, Kanban University (2015)",
      "Building High-Performing Teams, Stanford University (2020)",
      "An Introduction to Agile Project Management, Stanford University (2020)",
      "Swift & TDD/Unit tests, Managing projects with Scrum (Alura, 2015) · UX & Usability (Adaptworks, 2014)",
    ],
  },

  pt: {
    role: "Staff Software Engineer · Tech Lead · Scrum Master",
    location: "SF Bay Area, EUA",
    labels: {
      summary: "Resumo",
      skills: "Competências Técnicas",
      experience: "Experiência Profissional",
      ventures: "Empreendimentos",
      education: "Formação",
      languages: "Idiomas",
      certifications: "Certificações",
      client: "Cliente",
      tech: "Tecnologias",
      present: "Atual",
    },
    summary:
      "Engenheiro de software sênior com mais de 17 anos de experiência em todo o ciclo de desenvolvimento — UX, análise, design, desenvolvimento, testes e deploy. Atuei em projetos só de backend, de backend + frontend e de backend + mobile, como Desenvolvedor, Tech Lead ou Scrum Master / facilitador ágil, conforme a necessidade do time. Forte perfil empreendedor: engenheiro fundador na X4Fare e na PayAqui, cofundador da fleeber (hoje amy.network) e atualmente construindo a AtipicALI. Lidero pelo exemplo, gosto de trabalhar com pessoas não-técnicas e transformo ambiguidade em produtos entregues.",
    skills: [
      { group: "Backend", items: "Java (8–21), Spring Boot, Spring WebFlux, Kafka, Hibernate, Drools, Python, REST, JMS, SOAP" },
      { group: "Frontend & Mobile", items: "React, TypeScript, JavaScript, Flutter, Swift (iOS), Android, JSF, Wicket" },
      { group: "Cloud & Dados", items: "AWS (EC2, RDS, SQS, S3), Databricks, Oracle, SQL Server, PostgreSQL" },
      { group: "DevOps & Ferramentas", items: "CI/CD, GitHub Actions, Jenkins, Bamboo, Maven, Gradle, Git, Liquibase, JHipster" },
      { group: "IA & Práticas", items: "IA / LLMs, IA Agentic, GitHub Copilot, Codex, TDD/BDD, JUnit, Mockito, Scrum, Kanban" },
    ],
    experience: [
      {
        company: "Avenue Code",
        title: "Staff Software Engineer · Tech Lead",
        place: "SF Bay Area, EUA — Remoto",
        period: "2022 – Atual",
        bullets: [
          "Lidero iniciativas técnicas em supply chain, logística, engenharia de dados e programas de IA para organizações de varejo Fortune 500.",
          "Construí a prova de conceito de uma plataforma de regras interna estratégica, ajudando a liderança a validar a substituição de uma solução comercial e a estabelecer a base para futuras iniciativas de IA.",
          "Coordenei a migração de aproximadamente 20 microsserviços de Java 11 para Java 21, definindo diretrizes técnicas, documentação e práticas de rollout.",
          "Projetei e implementei um dashboard operacional de engenharia adotado por múltiplos times, dando visibilidade sobre saúde dos serviços, status de deploy e disponibilidade de ambientes.",
          "Implementei fluxos automatizados no Jira para acompanhamento de incidentes operacionais e monitoramento de serviços.",
          "Contribuí para práticas de engenharia assistida por IA através de workflows de desenvolvimento, prompts, documentação e padrões de implementação.",
          "Desenvolvi soluções de processamento e simulação de dados usando Python e Databricks para iniciativas de planejamento e forecasting no varejo.",
        ],
        tech: "Java, Spring Boot, Spring WebFlux, Python, Databricks, AWS, Kafka, Drools, SQL Server, Oracle, Jenkins, desenvolvimento assistido por IA",
      },
      {
        company: "X4Fare",
        title: "Engenheiro Fundador",
        place: "São Paulo, Brasil — Remoto",
        period: "2020 – 2021",
        bullets: [
          "Ajudei a construir uma startup de fintech de mobilidade em estágio inicial, do conceito aos deploys em produção.",
          "Entreguei aplicações de backend, web e mobile dando suporte a produtos de carteira digital e processamento de transações.",
          "Aprendi Flutter e me tornei um contribuidor-chave da plataforma mobile para acelerar a entrega do produto.",
          "Participei de contratação, entrevistas, onboarding e mentoria de engenheiros conforme o time crescia.",
          "Criei processos de onboarding que permitiam a novos desenvolvedores contribuir com código em produção em aproximadamente duas semanas.",
          "Atuei como referência técnica em discussões de backend, mobile e produto.",
          "Apoiei o deploy e a operação de sistemas em produção voltados ao cliente.",
        ],
        tech: "Java, Spring Boot, Flutter, React, AWS, JHipster, Liquibase, GitHub Actions",
      },
      {
        company: "Avenue Code",
        title: "Engenheiro de Software Sênior · Tech Lead",
        place: "São Paulo, Brasil → EUA",
        period: "2015 – 2020",
        bullets: [
          "SquareTrade: um dos três primeiros engenheiros a iniciar a conta no Brasil — o trabalho fez o time crescer para mais de 30 pessoas. Atuei em Merchant Integrations (Apache Camel, Apache Zookeeper) como Tech Lead, Scrum Master e 'Buddy' (papel gerencial de mentoria).",
          "Merchant e-Solutions: viajei para Redwood City, CA para ajudar a empresa a obter a certificação AMEX, trabalhando on-site.",
          "Williams Sonoma: construí microsserviços sobre uma camada de aplicação Sterling; ajudei o time a montar dashboards em JS/HTML puro e scripts em Bash.",
          "GAP · PIM / Data Governance: liderei e mentorei o time em testes unitários e de integração para Kafka, substituindo o catálogo de produtos (Pacman) pelo Stibo e publicando dados padronizados em um cluster Kafka; também atuei como Management Mentor.",
        ],
        tech: "Java, Spring Boot, Kafka, JMS, SOAP, Apache Camel, EJB, JUnit, Mockito, Gradle, Swagger, Bash, Jenkins, Oracle, SQL Server, PostgreSQL",
      },
      {
        company: "MAPS Soluções e Serviços",
        title: "Engenheiro de Software Sênior · Tech Lead",
        place: "São Paulo, Brasil",
        period: "2005 – 2015",
        bullets: [
          "Projetei e implementei um motor de cálculo de impostos usado para controle de passivo de fundos de investimento.",
          "Liderei o desenvolvimento de funcionalidades regulatórias e críticas de negócio para sistemas financeiros que atendiam clientes bancários.",
          "Atuei como tech lead, scrum master, product owner e mentor conforme a necessidade de cada projeto.",
          "Levantei requisitos diretamente com clientes, priorizei backlogs e traduzi regras de negócio em soluções de software.",
          "Mentorei aproximadamente vinte engenheiros ao longo de múltiplos projetos e times.",
          "Participei de discussões de arquitetura, planejamento técnico e coordenação de entregas para plataformas financeiras.",
        ],
        tech: "Java, Spring, Hibernate, Oracle, PostgreSQL, AWS, Wicket, Maven, Jenkins",
      },
      {
        company: "Faculdade Cásper Líbero",
        title: "Estagiário de TI",
        place: "São Paulo, Brasil",
        period: "2002 – 2005",
        bullets: [
          "Mantinha os laboratórios de informática da faculdade, dava suporte técnico aos alunos e automatizava rotinas administrativas.",
        ],
        tech: "Bash Scripting, JavaScript",
      },
    ],
    ventures: [
      {
        name: "AtipicALI",
        title: "Cofundador",
        period: "2025 – Atual",
        desc: "Projeto paralelo ativo, iniciado em 2025 em paralelo ao trabalho full-time, ainda em andamento.",
      },
      {
        name: "PayAqui",
        title: "Engenheiro Fundador · Mobile",
        period: "2018 – 2019",
        desc: "Engenheiro fundador de uma fintech de pagamentos tocada em paralelo. Projetei e construí os apps nativos Android e iOS de ponta a ponta — da arquitetura à publicação — participando também da descoberta de requisitos e UX, além de contribuir com o backend em Java.",
      },
      {
        name: "fleeber (hoje amy.network)",
        title: "Cofundador",
        period: "2013 – 2015",
        desc: "Cofundei uma rede social para músicos com três aplicações (app público, back-office e o ERP Studios). Responsável por todas as decisões técnicas e a maior parte do desenvolvimento, com abordagem BDD, motor de busca em Apache Lucene e infraestrutura na AWS. Continua hoje como amy.network.",
      },
    ],
    education: [
      { degree: "Bacharelado em Ciência da Computação", school: "Pontifícia Universidade Católica de São Paulo (PUC-SP)", period: "2002 – 2009" },
    ],
    languages: "Português (nativo/bilíngue) · Inglês (proficiência profissional plena)",
    certifications: [
      "PSM — Professional Scrum Master, Scrum.org (2017)",
      "MCD — Integration & API Associate, MuleSoft (2018)",
      "KMP I — Kanban Management Professional, Kanban University (2015)",
      "Building High-Performing Teams, Stanford University (2020)",
      "An Introduction to Agile Project Management, Stanford University (2020)",
      "Swift & TDD/testes unitários, Gestão de projetos com Scrum (Alura, 2015) · UX & Usabilidade (Adaptworks, 2014)",
    ],
  },
};
